/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  async redirects() {
    return [
      // Redirect old number page URLs to new /sayi/X format
      { source: '/1li-carpim-tablosu/', destination: '/sayi/1', permanent: true },
      { source: '/2li-carpim-tablosu/', destination: '/sayi/2', permanent: true },
      { source: '/3li-carpim-tablosu/', destination: '/sayi/3', permanent: true },
      { source: '/4li-carpim-tablosu/', destination: '/sayi/4', permanent: true },
      { source: '/5li-carpim-tablosu/', destination: '/sayi/5', permanent: true },
      { source: '/6li-carpim-tablosu/', destination: '/sayi/6', permanent: true },
      { source: '/7li-carpim-tablosu/', destination: '/sayi/7', permanent: true },
      { source: '/8li-carpim-tablosu/', destination: '/sayi/8', permanent: true },
      { source: '/9li-carpim-tablosu/', destination: '/sayi/9', permanent: true },
      { source: '/10li-carpim-tablosu/', destination: '/sayi/10', permanent: true },
      { source: '/11li-carpim-tablosu/', destination: '/sayi/11', permanent: true },
      { source: '/12-li-carpim-tablosu/', destination: '/sayi/12', permanent: true },
      { source: '/13li-carpim-tablosu/', destination: '/sayi/13', permanent: true },
      { source: '/14-li-carpim-tablosu/', destination: '/sayi/14', permanent: true },
      { source: '/15-li-carpim-tablosu/', destination: '/sayi/15', permanent: true },
      { source: '/16-li-carpim-tablosu/', destination: '/sayi/16', permanent: true },
      { source: '/17li-carpim-tablosu/', destination: '/sayi/17', permanent: true },
      { source: '/18li-carpim-tablosu/', destination: '/sayi/18', permanent: true },
      { source: '/19-li-carpim-tablosu/', destination: '/sayi/19', permanent: true },
      { source: '/20-li-carpim-tablosu/', destination: '/sayi/20', permanent: true },
      { source: '/21-li-carpim-tablosu/', destination: '/sayi/21', permanent: true },
      { source: '/22-li-carpim-tablosu/', destination: '/sayi/22', permanent: true },
      { source: '/23-li-carpim-tablosu/', destination: '/sayi/23', permanent: true },
      { source: '/24-li-carpim-tablosu/', destination: '/sayi/24', permanent: true },
      { source: '/25li-carpim-tablosu/', destination: '/sayi/25', permanent: true },
      { source: '/26-li-carpim-tablosu/', destination: '/sayi/26', permanent: true },
      { source: '/27-li-carpim-tablosu/', destination: '/sayi/27', permanent: true },
      { source: '/28-li-carpim-tablosu/', destination: '/sayi/28', permanent: true },
      { source: '/29-li-carpim-tablosu/', destination: '/sayi/29', permanent: true },
      { source: '/30-li-carpim-tablosu/', destination: '/sayi/30', permanent: true },
      { source: '/31-ler-carpim-tablosu/', destination: '/sayi/31', permanent: true },
      { source: '/32-ler-carpim-tablosu/', destination: '/sayi/32', permanent: true },
      { source: '/33-ler-carpim-tablosu/', destination: '/sayi/33', permanent: true },
      { source: '/34-ler-carpim-tablosu/', destination: '/sayi/34', permanent: true },
      { source: '/35-ler-carpim-tablosu/', destination: '/sayi/35', permanent: true },
      { source: '/36-ler-carpim-tablosu/', destination: '/sayi/36', permanent: true },
      { source: '/37-ler-carpim-tablosu/', destination: '/sayi/37', permanent: true },
      { source: '/38-ler-carpim-tablosu/', destination: '/sayi/38', permanent: true },
      { source: '/39-ler-carpim-tablosu/', destination: '/sayi/39', permanent: true },
      { source: '/40-ler-carpim-tablosu/', destination: '/sayi/40', permanent: true },
    ];
  },
}

module.exports = nextConfig
