/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  async redirects() {
    return [
      // Redirect old number page URLs to new /sayi/X format
      { source: '/1li-carpim-tablosu/', destination: '/sayi/1', permanent: true },
      { source: '/2li-carpim-tablosu/', destination: '/sayi/2', permanent: true },
      { source: '/3li-carpim-tablosu/', destination: '/sayi/3', permanent: true },
      { source: '/4li-carpim-tablosu/', destination: '/sayi/4', permanent: true },
      { source: '/5li-carpim-tablosu/', destination: '/sayi/5', permanent: true },
      { source: '/6li-carpim-tablosu/', destination: '/sayi/6', permanent: true },
      { source: '/7li-carpim-tablosu/', destination: '/sayi/7', permanent: true },
      { source: '/8li-carpim-tablosu/', destination: '/sayi/8', permanent: true },
      { source: '/9li-carpim-tablosu/', destination: '/sayi/9', permanent: true },
      { source: '/10li-carpim-tablosu/', destination: '/sayi/10', permanent: true },
      { source: '/11li-carpim-tablosu/', destination: '/sayi/11', permanent: true },
      { source: '/12-li-carpim-tablosu/', destination: '/sayi/12', permanent: true },
      { source: '/13li-carpim-tablosu/', destination: '/sayi/13', permanent: true },
      { source: '/14-li-carpim-tablosu/', destination: '/sayi/14', permanent: true },
      { source: '/15-li-carpim-tablosu/', destination: '/sayi/15', permanent: true },
      { source: '/16-li-carpim-tablosu/', destination: '/sayi/16', permanent: true },
      { source: '/17li-carpim-tablosu/', destination: '/sayi/17', permanent: true },
      { source: '/18li-carpim-tablosu/', destination: '/sayi/18', permanent: true },
      { source: '/19-li-carpim-tablosu/', destination: '/sayi/19', permanent: true },
      { source: '/20-li-carpim-tablosu/', destination: '/sayi/20', permanent: true },
      { source: '/21-li-carpim-tablosu/', destination: '/sayi/21', permanent: true },
      { source: '/22-li-carpim-tablosu/', destination: '/sayi/22', permanent: true },
      { source: '/23-li-carpim-tablosu/', destination: '/sayi/23', permanent: true },
      { source: '/24-li-carpim-tablosu/', destination: '/sayi/24', permanent: true },
      { source: '/25li-carpim-tablosu/', destination: '/sayi/25', permanent: true },
      { source: '/26-li-carpim-tablosu/', destination: '/sayi/26', permanent: true },
      { source: '/27-li-carpim-tablosu/', destination: '/sayi/27', permanent: true },
      { source: '/28-li-carpim-tablosu/', destination: '/sayi/28', permanent: true },
      { source: '/29-li-carpim-tablosu/', destination: '/sayi/29', permanent: true },
      { source: '/30-li-carpim-tablosu/', destination: '/sayi/30', permanent: true },
      { source: '/31-ler-carpim-tablosu/', destination: '/sayi/31', permanent: true },
      { source: '/32-ler-carpim-tablosu/', destination: '/sayi/32', permanent: true },
      { source: '/33-ler-carpim-tablosu/', destination: '/sayi/33', permanent: true },
      { source: '/34-ler-carpim-tablosu/', destination: '/sayi/34', permanent: true },
      { source: '/35-ler-carpim-tablosu/', destination: '/sayi/35', permanent: true },
      { source: '/36-ler-carpim-tablosu/', destination: '/sayi/36', permanent: true },
      { source: '/37-ler-carpim-tablosu/', destination: '/sayi/37', permanent: true },
      { source: '/38-ler-carpim-tablosu/', destination: '/sayi/38', permanent: true },
      { source: '/39-ler-carpim-tablosu/', destination: '/sayi/39', permanent: true },
      { source: '/40-ler-carpim-tablosu/', destination: '/sayi/40', permanent: true },
      { source: '/41-ler-carpim-tablosu/', destination: '/sayi/41', permanent: true },
      { source: '/42-ler-carpim-tablosu/', destination: '/sayi/42', permanent: true },
      { source: '/43-ler-carpim-tablosu/', destination: '/sayi/43', permanent: true },
      { source: '/44-ler-carpim-tablosu/', destination: '/sayi/44', permanent: true },
      { source: '/45-ler-carpim-tablosu/', destination: '/sayi/45', permanent: true },
      { source: '/46-ler-carpim-tablosu/', destination: '/sayi/46', permanent: true },
      { source: '/47-ler-carpim-tablosu/', destination: '/sayi/47', permanent: true },
      { source: '/48-ler-carpim-tablosu/', destination: '/sayi/48', permanent: true },
      { source: '/49-ler-carpim-tablosu/', destination: '/sayi/49', permanent: true },
      { source: '/50-ler-carpim-tablosu/', destination: '/sayi/50', permanent: true },
      { source: '/51-ler-carpim-tablosu/', destination: '/sayi/51', permanent: true },
      { source: '/52-ler-carpim-tablosu/', destination: '/sayi/52', permanent: true },
      { source: '/53-ler-carpim-tablosu/', destination: '/sayi/53', permanent: true },
      { source: '/54-ler-carpim-tablosu/', destination: '/sayi/54', permanent: true },
      { source: '/55-ler-carpim-tablosu/', destination: '/sayi/55', permanent: true },
      { source: '/56-ler-carpim-tablosu/', destination: '/sayi/56', permanent: true },
      { source: '/57-ler-carpim-tablosu/', destination: '/sayi/57', permanent: true },
      { source: '/58-ler-carpim-tablosu/', destination: '/sayi/58', permanent: true },
      { source: '/59-ler-carpim-tablosu/', destination: '/sayi/59', permanent: true },
      { source: '/60-ler-carpim-tablosu/', destination: '/sayi/60', permanent: true },
      { source: '/61-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/61', permanent: true },
      { source: '/62-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/62', permanent: true },
      { source: '/63-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/63', permanent: true },
      { source: '/64-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/64', permanent: true },
      { source: '/65-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/65', permanent: true },
      { source: '/66-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/66', permanent: true },
      { source: '/67-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/67', permanent: true },
      { source: '/68-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/68', permanent: true },
      { source: '/69-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/69', permanent: true },
      { source: '/70-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/70', permanent: true },
      { source: '/71-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/71', permanent: true },
      { source: '/72-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/72', permanent: true },
      { source: '/73-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/73', permanent: true },
      { source: '/74-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/74', permanent: true },
      { source: '/75-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/75', permanent: true },
      { source: '/76-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/76', permanent: true },
      { source: '/77-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/77', permanent: true },
      { source: '/78-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/78', permanent: true },
      { source: '/79-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/79', permanent: true },
      { source: '/80-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/80', permanent: true },
      { source: '/81-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/81', permanent: true },
      { source: '/82-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/82', permanent: true },
      { source: '/83-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/83', permanent: true },
      { source: '/84-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/84', permanent: true },
      { source: '/85-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/85', permanent: true },
      { source: '/86-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/86', permanent: true },
      { source: '/87-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/87', permanent: true },
      { source: '/88-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/88', permanent: true },
      { source: '/89-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/89', permanent: true },
      { source: '/90-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/90', permanent: true },
      { source: '/91-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/91', permanent: true },
      { source: '/92-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/92', permanent: true },
      { source: '/93-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/93', permanent: true },
      { source: '/94-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/94', permanent: true },
      { source: '/95-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/95', permanent: true },
      { source: '/96-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/96', permanent: true },
      { source: '/97-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/97', permanent: true },
      { source: '/98-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/98', permanent: true },
      { source: '/99-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/99', permanent: true },
      { source: '/100-ler-carpim-tablosu-oyunlar-alistirmalar/', destination: '/sayi/100', permanent: true },
    ];
  },
}

module.exports = nextConfig
